#pragma once

#define ENEMY_JUMP_VELOCITY 800.0f
#define AIR_CONTROL_FACTOR 0.65f

extern float deltaTime;
extern float gravity;

#define PROJECTILE_CLEANUP_THRESHOLD 5000.0f

#define PLAYER_AR_BULLET_SIZE 50.0f
#define PLAYER_AR_SPEED 1500.0f
#define PLAYER_AR_RELOAD 0.3f

#define PLAYER_SHOTGUN_PELLET_SIZE 50.0f
#define PLAYER_SHOTGUN_SPEED 1200.0f
#define PLAYER_SHOTGUN_RELOAD 0.8f
#define PLAYER_SHOTGUN_PELLET_COUNT 8
#define PLAYER_SHOTGUN_SPREAD 0.4f

#define PLAYER_ROCKET_SIZE 100.0f
#define PLAYER_ROCKET_SPEED 800.0f
#define PLAYER_ROCKET_RELOAD 1.5f

#define ENEMY_BULLET_SIZE 50.0f
#define ENEMY_BULLET_SPEED 1.0f
