#pragma once

#define ENEMY_JUMP_VELOCITY 800.0f
#define AIR_CONTROL_FACTOR  0.65f

extern float deltaTime;
extern float gravity;

#define PROJECTILE_CLEANUP_THRESHOLD 5000.0f
#define PROJECTILE_CLEANUP_THRESHOLD_SQUARED \
  PROJECTILE_CLEANUP_THRESHOLD* PROJECTILE_CLEANUP_THRESHOLD

#define INITIAL_GAME_TIMER 5000.0f
#define MELEE_KILL_TIMER_REWARD 10.0f
#define RANGED_KILL_TIMER_REWARD 5.0f
extern float gameTimer;
extern float exitTimer;

#define PLAYER_START_X 100.0f
#define PLAYER_START_Y 100.0f
#define PLAYER_SPAWN_X 175.0f
#define PLAYER_SPAWN_Y 400.0f
#define PLAYER_WIDTH 100.0f
#define PLAYER_HEIGHT 100.0f
#define PLAYER_ACCELERATION 2000.0f
#define PLAYER_FRICTION 1500.0f
#define PLAYER_MAX_SPEED 3000.0f
#define PLAYER_JUMP_STRENGTH 600.0f
#define PLAYER_HP 100000
#define PLAYER_COLLISION_BUFFER 10.0f

#define PLAYER_EXPLOSION_DURATION 0.5f
#define PLAYER_ROCKET_EXPLOSION_RADIUS 100

#define STARTING_PILLAR_WIDTH 850.0f
#define STARTING_PILLAR_HEIGHT 850.0f
#define STARTING_PILLAR_X -200.0f
#define STARTING_PILLAR_Y 500.0f

#define PILLAR_COUNT 60
#define PILLAR_GEN_ATTEMPTS 100
#define PILLAR_MIN_WIDTH 600
#define PILLAR_MAX_WIDTH 900
#define PILLAR_MIN_HEIGHT 600
#define PILLAR_MAX_HEIGHT 800
#define PILLAR_MIN_X 2000
#define PILLAR_MAX_X 50000

#define PLAYER_AR_BULLET_SIZE 20.0f
#define PLAYER_AR_SPEED       1500.0f
#define PLAYER_AR_RELOAD      0.3f
#define PLAYER_AR_DAMAGE      20

#define PLAYER_SHOTGUN_PELLET_SIZE  20.0f
#define PLAYER_SHOTGUN_SPEED        1200.0f
#define PLAYER_SHOTGUN_RELOAD       0.8f
#define PLAYER_SHOTGUN_PELLET_COUNT 8
#define PLAYER_SHOTGUN_SPREAD       0.4f
#define PLAYER_SHOTGUN_DAMAGE       25

#define PLAYER_ROCKET_SIZE   100.0f
#define PLAYER_ROCKET_SPEED  800.0f
#define PLAYER_ROCKET_RELOAD 1.5f
#define PLAYER_ROCKET_DAMAGE 160

#define ENEMY_BULLET_SIZE   25.0f
#define ENEMY_BULLET_SPEED  800.0f
#define ENEMY_BULLET_DAMAGE 10

#define ENEMY_MELEE_DAMAGE 20

typedef enum {MAIN_MENU = 0, GAME = 1, DEAD = 2, WON = 3} GameState;
